[build]
command = "npm run build"
publish = "dist"

[deploy]
strategy = "yandex-object-storage"
bucket = "schedulettgt-static"
region = "ru-central1"

[[headers]]
for = "/*"
[headers.values]
Cache-Control = "public, max-age=3600"

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"